# The URL the site will be built for
base_url = "https://tylerschmidtke.com"
generate_feed = true
compile_sass = true
minify_html = true

title = "Tyler Schmidtke"
description = "A personal website for Tyler Schmidtke including a blog, resume, and more."
theme = "tabi"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
favicon_emoji = "🌊"

menu = [
    { name = "Resume", url = "resume", trailing_slash = true },
    { name = "Blog", url = "blog"},
]

socials = [
    { name = "github", url = "https://github.com/tylerschmidtke/", icon = "github" },
    { name = "mastodon", url = "https://mastodon.social/@tylerschmidtke", icon = "mastodon" },
    { name = "linkedin", url = "https://linkedin.com/in/tylerschmidtke", icon = "linkedin" },
]

allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
    { directive = "connect-src", domains = ["https://plausible.io"] }
]

# giscus support for comments. https://giscus.app
# Setup instructions: https://welpo.github.io/tabi/blog/comments/#setup
[extra.giscus]
enabled_for_all_posts = false  # Enables giscus on all posts. It can be enabled on individual posts by setting `giscus = true` in the [extra] section of a post's front matter.
automatic_loading = true  # If set to false, a "Load comments" button will be shown.
repo = "tylerschmidtke/tylerschmidtke.com"
repo_id = "R_kgDOKFgkBQ"  # Find this value in https://giscus.app/
category = "General"
category_id = "DIC_kwDOKFgkBc4CYop2"  # Find this value in https://giscus.app/
mapping = "slug"  # Available: pathname; url; title; slug. "slug" will use the post's filename (slug); this is the only way to share comments between languages.
strict_title_matching = 1  # 1 to enable, 0 to disable. https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-strict
enable_reactions = 1  # 1 to enable, 0 to disable.
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""  # Leave blank to match the page's language.
lazy_loading = true